---
version: "3.7"

services:
  e2e-allure:
    image: frankescobar/allure-docker-service
    restart: unless-stopped
    volumes:
      - "./allure-results:/app/allure-results"
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1
