---
version: "3.7"

networks:
  selenium:

services:
  chrome:
    image: ${CHROMEDRIVER_IMAGE}
    shm_size: 2gb
    networks:
      - selenium
    ports:
      - '7900:7900'
      - '4444:4444'

  e2e-allure:
    image: frankescobar/allure-docker-service:2.21.0
    restart: unless-stopped
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    ports:
      - "5050:5050"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 10
      KEEP_HISTORY: 1

  e2e-python:
    build:
      context: .
      dockerfile: ./docker/local/python/Dockerfile
    tty: true
    networks:
      - selenium
    volumes:
      - "./:/var/www"
